services:
  php:
    build: .
    container_name: laravel-php
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: false
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: laravel-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
